Repository cognitedata/indsl, pull requests merged in 2023-12, with the labels that each got.

#69 fix: upgrade pandas to 2.1.4
  CONTRIBUTING.md
  poetry.lock
  pyproject.toml
  tests/oil_and_gas/test_live_fluid_properties.py
Labels: auto-merge, auto-update

#73 fix: Fix unit test publish
  .github/workflows/code-quality.yaml
Labels: auto-update

#74 fix: Update note about availability after open sourcing
  docs-source/source/contribute.rst
Labels: auto-merge

#79 chore: Updating code owners
  .github/CODEOWNERS
Labels: auto-merge, auto-update
